package BookSearch;

import pesquisaLivro.*;
import usuario.*;
import livro.*;

import java.io.FileNotFoundException;
import javax.swing.JLabel;

public class BookSearch extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    Usuario myUsuario;
    PesquisaLivro  myPesquisa;
    public BookSearch() {
        initComponents();
        myUsuario = new Usuario();
        myPesquisa = new PesquisaLivro(myUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generoChoiceFrame = new javax.swing.JFrame();
        fundoGenero = new javax.swing.JPanel();
        generoRomanceButton = new javax.swing.JButton();
        generoFantasiaButton = new javax.swing.JButton();
        generoTerrorButton = new javax.swing.JButton();
        generoFiccaoButton = new javax.swing.JButton();
        perguntaGenero = new javax.swing.JLabel();
        nomeFormLabelGenero = new javax.swing.JLabel();
        outputFrame = new javax.swing.JFrame();
        fundoOutput = new javax.swing.JPanel();
        nomeFormLabelLivros = new javax.swing.JLabel();
        outputInfoUsuario = new javax.swing.JLabel();
        outputLivro1 = new javax.swing.JLabel();
        outputLivro2 = new javax.swing.JLabel();
        outputLivro3 = new javax.swing.JLabel();
        outputLivro4 = new javax.swing.JLabel();
        outputLivro5 = new javax.swing.JLabel();
        fundoMain = new javax.swing.JPanel();
        idadeComboBox = new javax.swing.JComboBox<>();
        nomeUsuarioResp1 = new javax.swing.JTextField();
        tipoPesquisaIniciante = new javax.swing.JButton();
        tipoPesquisaAvancado = new javax.swing.JButton();
        idadeLabel = new javax.swing.JLabel();
        tipoPesquisaLabel = new javax.swing.JLabel();
        nomeFormLabelMain = new javax.swing.JLabel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        mensagemErro = new javax.swing.JLabel();

        generoChoiceFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        generoChoiceFrame.setMinimumSize(new java.awt.Dimension(640, 500));

        fundoGenero.setBackground(new java.awt.Color(102, 102, 102));
        fundoGenero.setMinimumSize(new java.awt.Dimension(640, 500));

        generoRomanceButton.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 36)); // NOI18N
        generoRomanceButton.setText("Romance");
        generoRomanceButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BookSearch/bookIcon.png"))); // NOI18N
        generoRomanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoRomanceButtonActionPerformed(evt);
            }
        });

        generoFantasiaButton.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 36)); // NOI18N
        generoFantasiaButton.setText("Fantasia");
        generoFantasiaButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BookSearch/bookIcon.png"))); // NOI18N
        generoFantasiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoFantasiaButtonActionPerformed(evt);
            }
        });

        generoTerrorButton.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 36)); // NOI18N
        generoTerrorButton.setText("Terror");
        generoTerrorButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BookSearch/bookIcon.png"))); // NOI18N
        generoTerrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoTerrorButtonActionPerformed(evt);
            }
        });

        generoFiccaoButton.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 36)); // NOI18N
        generoFiccaoButton.setText("Ficção Científica");
        generoFiccaoButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BookSearch/bookIcon.png"))); // NOI18N
        generoFiccaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoFiccaoButtonActionPerformed(evt);
            }
        });

        perguntaGenero.setBackground(new java.awt.Color(255, 255, 255));
        perguntaGenero.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        perguntaGenero.setForeground(new java.awt.Color(255, 255, 255));
        perguntaGenero.setText("Que gênero de Livro mais te agrada?");

        nomeFormLabelGenero.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nomeFormLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        nomeFormLabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeFormLabelGenero.setText("BookSearch (Gênero)");

        javax.swing.GroupLayout fundoGeneroLayout = new javax.swing.GroupLayout(fundoGenero);
        fundoGenero.setLayout(fundoGeneroLayout);
        fundoGeneroLayout.setHorizontalGroup(
            fundoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoGeneroLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(fundoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(generoTerrorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generoFiccaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE))
                .addGap(46, 46, 46))
            .addGroup(fundoGeneroLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(fundoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFormLabelGenero)
                    .addGroup(fundoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(perguntaGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                        .addComponent(generoRomanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generoFantasiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fundoGeneroLayout.setVerticalGroup(
            fundoGeneroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoGeneroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nomeFormLabelGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(perguntaGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(generoRomanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(generoFantasiaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(generoTerrorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(generoFiccaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout generoChoiceFrameLayout = new javax.swing.GroupLayout(generoChoiceFrame.getContentPane());
        generoChoiceFrame.getContentPane().setLayout(generoChoiceFrameLayout);
        generoChoiceFrameLayout.setHorizontalGroup(
            generoChoiceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        generoChoiceFrameLayout.setVerticalGroup(
            generoChoiceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        outputFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        outputFrame.setMinimumSize(new java.awt.Dimension(1024, 768));

        fundoOutput.setBackground(new java.awt.Color(102, 102, 102));
        fundoOutput.setMinimumSize(new java.awt.Dimension(1024, 768));
        fundoOutput.setPreferredSize(new java.awt.Dimension(1024, 768));

        nomeFormLabelLivros.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nomeFormLabelLivros.setForeground(new java.awt.Color(255, 255, 255));
        nomeFormLabelLivros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeFormLabelLivros.setText("BookSearch (Livros)");

        outputInfoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputInfoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        outputInfoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputInfoUsuario.setText("Info Usuário");

        outputLivro1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLivro1.setForeground(new java.awt.Color(255, 255, 255));
        outputLivro1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputLivro1.setText("Livro não encontrado");

        outputLivro2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLivro2.setForeground(new java.awt.Color(255, 255, 255));
        outputLivro2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputLivro2.setText("Livro não encontrado");

        outputLivro3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLivro3.setForeground(new java.awt.Color(255, 255, 255));
        outputLivro3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputLivro3.setText("Livro não encontrado");

        outputLivro4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLivro4.setForeground(new java.awt.Color(255, 255, 255));
        outputLivro4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputLivro4.setText("Livro não encontrado");

        outputLivro5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        outputLivro5.setForeground(new java.awt.Color(255, 255, 255));
        outputLivro5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outputLivro5.setText("Livro não encontrado");

        javax.swing.GroupLayout fundoOutputLayout = new javax.swing.GroupLayout(fundoOutput);
        fundoOutput.setLayout(fundoOutputLayout);
        fundoOutputLayout.setHorizontalGroup(
            fundoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoOutputLayout.createSequentialGroup()
                .addGroup(fundoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoOutputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(fundoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputLivro2)
                            .addComponent(outputLivro1)
                            .addComponent(outputLivro3)
                            .addComponent(outputLivro4)
                            .addComponent(outputLivro5)))
                    .addGroup(fundoOutputLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(outputInfoUsuario))
                    .addGroup(fundoOutputLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nomeFormLabelLivros)))
                .addContainerGap(784, Short.MAX_VALUE))
        );
        fundoOutputLayout.setVerticalGroup(
            fundoOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoOutputLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nomeFormLabelLivros)
                .addGap(18, 18, 18)
                .addComponent(outputInfoUsuario)
                .addGap(136, 136, 136)
                .addComponent(outputLivro1)
                .addGap(18, 18, 18)
                .addComponent(outputLivro2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputLivro3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputLivro4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(outputLivro5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout outputFrameLayout = new javax.swing.GroupLayout(outputFrame.getContentPane());
        outputFrame.getContentPane().setLayout(outputFrameLayout);
        outputFrameLayout.setHorizontalGroup(
            outputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        outputFrameLayout.setVerticalGroup(
            outputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        fundoMain.setBackground(new java.awt.Color(102, 102, 102));
        fundoMain.setMinimumSize(new java.awt.Dimension(640, 500));
        fundoMain.setPreferredSize(new java.awt.Dimension(640, 500));

        idadeComboBox.setFont(new java.awt.Font("JetBrains Mono SemiBold", 0, 18)); // NOI18N
        idadeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        idadeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idadeComboBoxActionPerformed(evt);
            }
        });

        nomeUsuarioResp1.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        nomeUsuarioResp1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        nomeUsuarioResp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeUsuarioResp1ActionPerformed(evt);
            }
        });

        tipoPesquisaIniciante.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        tipoPesquisaIniciante.setText("Iniciante");
        tipoPesquisaIniciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPesquisaInicianteActionPerformed(evt);
            }
        });

        tipoPesquisaAvancado.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        tipoPesquisaAvancado.setText("Avançado");
        tipoPesquisaAvancado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPesquisaAvancadoActionPerformed(evt);
            }
        });

        idadeLabel.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        idadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        idadeLabel.setText("Idade: ");

        tipoPesquisaLabel.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        tipoPesquisaLabel.setForeground(new java.awt.Color(255, 255, 255));
        tipoPesquisaLabel.setText("Quão ávido leitor você se considera?");

        nomeFormLabelMain.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        nomeFormLabelMain.setForeground(new java.awt.Color(255, 255, 255));
        nomeFormLabelMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeFormLabelMain.setText("BookSearch");

        nomeUsuarioLabel.setFont(new java.awt.Font("JetBrains Mono NL SemiBold", 0, 24)); // NOI18N
        nomeUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeUsuarioLabel.setText("Nome de Usuário:");
        nomeUsuarioLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        mensagemErro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mensagemErro.setForeground(new java.awt.Color(255, 51, 51));
        mensagemErro.setText(" ");

        javax.swing.GroupLayout fundoMainLayout = new javax.swing.GroupLayout(fundoMain);
        fundoMain.setLayout(fundoMainLayout);
        fundoMainLayout.setHorizontalGroup(
            fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoMainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeFormLabelMain)
                    .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tipoPesquisaLabel)
                        .addGroup(fundoMainLayout.createSequentialGroup()
                            .addComponent(idadeLabel)
                            .addGap(18, 18, 18)
                            .addComponent(idadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(mensagemErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundoMainLayout.createSequentialGroup()
                            .addComponent(tipoPesquisaIniciante, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoPesquisaAvancado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundoMainLayout.createSequentialGroup()
                            .addComponent(nomeUsuarioLabel)
                            .addGap(18, 18, 18)
                            .addComponent(nomeUsuarioResp1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        fundoMainLayout.setVerticalGroup(
            fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoMainLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(nomeFormLabelMain)
                .addGap(54, 54, 54)
                .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUsuarioLabel)
                    .addComponent(nomeUsuarioResp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeLabel)
                    .addComponent(idadeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tipoPesquisaLabel)
                .addGap(18, 18, 18)
                .addGroup(fundoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoPesquisaIniciante)
                    .addComponent(tipoPesquisaAvancado))
                .addGap(18, 18, 18)
                .addComponent(mensagemErro)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tipoPesquisaInicianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPesquisaInicianteActionPerformed
        // TODO add your handling code here:
        myUsuario.setTipoLeitor(TipoDeLeitor.Simples); 
        myUsuario.setNomeLeitor(nomeUsuarioResp1.getText()); 
        
        String valorIdade = idadeComboBox.getSelectedItem().toString();
        if(valorIdade.contains("-")) {
            valorIdade = "-1";
        }
        myUsuario.setIdadeLeitor(Integer.parseInt(valorIdade));  // Pegando a idade e convertendo para Int
        
        if(myUsuario.getNomeLeitor().length() > 0 && myUsuario.getIdadeLeitor() >= 0)
        {
            trocarTela(generoChoiceFrame, this, 640, 500);
        } 
            
        else 
        {
            mensagemErro.setText("É necessário preencher as informações!");
        }
    }//GEN-LAST:event_tipoPesquisaInicianteActionPerformed

    private void tipoPesquisaAvancadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPesquisaAvancadoActionPerformed
        // TODO add your handling code here:
        myUsuario.setTipoLeitor(TipoDeLeitor.Avancado); 
        myUsuario.setNomeLeitor(nomeUsuarioResp1.getText()); 
        
        String valorIdade = idadeComboBox.getSelectedItem().toString();
        if(valorIdade.contains("-")) {
            valorIdade = "-1";
        }
        myUsuario.setIdadeLeitor(Integer.parseInt(valorIdade)); // Pegando a idade e convertendo para Int
        
        if(myUsuario.getNomeLeitor().length() > 0 && myUsuario.getIdadeLeitor() >= 0)
        {
            trocarTela(generoChoiceFrame, this, 640, 500);
        } 
        else 
        {
            mensagemErro.setText("É necessário preencher as informações!");
        }
        
    }//GEN-LAST:event_tipoPesquisaAvancadoActionPerformed

    private void nomeUsuarioResp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeUsuarioResp1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomeUsuarioResp1ActionPerformed

    private void idadeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idadeComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idadeComboBoxActionPerformed

    private void generoRomanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoRomanceButtonActionPerformed
        // TODO add your handling code here:
        myUsuario.setGeneroLeitor(GeneroLivro.Romance); 
       
        
        trocarTela(outputFrame, generoChoiceFrame, 1024, 768);
        
        try {
            myPesquisa.lerCsv();
        } catch (FileNotFoundException ex) {
            System.out.println("Csv nao encontrado! Erro: " + ex.getMessage());
      
        }
        mostrarLivro();
      
    }//GEN-LAST:event_generoRomanceButtonActionPerformed

    private void generoFantasiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoFantasiaButtonActionPerformed
        // TODO add your handling code here:
        myUsuario.setGeneroLeitor(GeneroLivro.Fantasia);
        
        
        trocarTela(outputFrame, generoChoiceFrame, 1024, 768);
        
        try {
            myPesquisa.lerCsv();
        } catch (FileNotFoundException ex) {
            System.out.println("Csv nao encontrado! Erro: " + ex.getMessage());
        }
        mostrarLivro();
    }//GEN-LAST:event_generoFantasiaButtonActionPerformed

    private void generoTerrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoTerrorButtonActionPerformed
        // TODO add your handling code here:
        myUsuario.setGeneroLeitor(GeneroLivro.Terror);
        
        
        trocarTela(outputFrame, generoChoiceFrame, 1024, 768);
        
        try {
            myPesquisa.lerCsv();
        } catch (FileNotFoundException ex) {
            System.out.println("Csv nao encontrado! Erro: " + ex.getMessage());
        }
        mostrarLivro();
    }//GEN-LAST:event_generoTerrorButtonActionPerformed

    private void generoFiccaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoFiccaoButtonActionPerformed
        // TODO add your handling code here:
        myUsuario.setGeneroLeitor(GeneroLivro.FiccaoCientifica);
       
        
        trocarTela(outputFrame, generoChoiceFrame, 1024, 720);
        
        try {
            myPesquisa.lerCsv();
        } catch (FileNotFoundException ex) {
            System.out.println("Csv nao encontrado! Erro: " + ex.getMessage());
        }
        mostrarLivro();
    }//GEN-LAST:event_generoFiccaoButtonActionPerformed
    private void trocarTela(javax.swing.JFrame telaEscolha, javax.swing.JFrame telaAtual, int width, int height)
    {
        telaAtual.setVisible(false);
        telaEscolha.setSize(width, height);
        telaEscolha.setVisible(true);
    }
    
    private void mostrarLivro()
    {
        outputInfoUsuario.setText(myUsuario.toString());
        try
        {
            outputLivro1.setText(myPesquisa.recomendarLivro().get(0).toString()); // oque vai ser (Livro 1)
            outputLivro2.setText(myPesquisa.recomendarLivro().get(1).toString());// (Livro 2)
            outputLivro3.setText(myPesquisa.recomendarLivro().get(2).toString()); // livro 3 
            outputLivro4.setText(myPesquisa.recomendarLivro().get(3).toString()); // livro 4
            outputLivro5.setText(myPesquisa.recomendarLivro().get(4).toString()); // livro 5
        }
        catch(IndexOutOfBoundsException exc)
        {
            System.out.println("Out of bounds: Livros não encontrados");
        }
            
    }
        
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearch().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fundoGenero;
    private javax.swing.JPanel fundoMain;
    private javax.swing.JPanel fundoOutput;
    private javax.swing.JFrame generoChoiceFrame;
    private javax.swing.JButton generoFantasiaButton;
    private javax.swing.JButton generoFiccaoButton;
    private javax.swing.JButton generoRomanceButton;
    private javax.swing.JButton generoTerrorButton;
    private javax.swing.JComboBox<String> idadeComboBox;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JLabel mensagemErro;
    private javax.swing.JLabel nomeFormLabelGenero;
    private javax.swing.JLabel nomeFormLabelLivros;
    private javax.swing.JLabel nomeFormLabelMain;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JTextField nomeUsuarioResp1;
    private javax.swing.JFrame outputFrame;
    private javax.swing.JLabel outputInfoUsuario;
    private javax.swing.JLabel outputLivro1;
    private javax.swing.JLabel outputLivro2;
    private javax.swing.JLabel outputLivro3;
    private javax.swing.JLabel outputLivro4;
    private javax.swing.JLabel outputLivro5;
    private javax.swing.JLabel perguntaGenero;
    private javax.swing.JButton tipoPesquisaAvancado;
    private javax.swing.JButton tipoPesquisaIniciante;
    private javax.swing.JLabel tipoPesquisaLabel;
    // End of variables declaration//GEN-END:variables
}
